export const cartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_ITEM',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',
    CLEAR_CART_SUCCESS: 'CLEAR_CART_SUCCESS',
    CLEAR_CART_FAILURE: 'CLEAR_CART_FAILURE'
}